### ISSUE TITLE
nested scrolling when using recyclerview

### ISSUE THREAD

**Issue by OfekAshkenazi** [fiskurgit/SimpleViewPager#11]
I'm using the SimpleViewPager inside recyclerview and I get this error - 

>  FATAL EXCEPTION: main
                                                                                 Process: ofeksprojects.ofek.com.nightout, PID: 30212
                                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.widget.LinearLayout.getChildAt(int)' on a null object reference
                                                                                     at eu.fiskur.simpleviewpager.SimpleViewPager.setIndicator(SimpleViewPager.java:217)
                                                                                     at eu.fiskur.simpleviewpager.SimpleViewPager.onLayout(SimpleViewPager.java:243)
                                                                                     at android.view.View.layout(View.java:16694)
                                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                     at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1495)
                                                                                     at android.view.View.layout(View.java:16694)
                                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                     at android.view.View.layout(View.java:16694)
                                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                     at android.support.v7.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:8994)
                                                                                     at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:685)
                                                                                     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                                                     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:585)
                                                                                     at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                                     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                                     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
                                                                                     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
                                                                                     at android.view.View.layout(View.java:16694)
                                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                                     at android.view.View.layout(View.java:16694)
                                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                     at android.view.View.layout(View.java:16694)
                                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                                     at android.view.View.layout(View.java:16694)
                                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                     at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
                                                                                     at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                                     at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
                                                                                     at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:874)
                                                                                     at android.view.View.layout(View.java:16694)
                                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                     at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1172)
                                                                                     at android.view.View.layout(View.java:16694)
                                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                     at android.view.View.layout(View.java:16694)
                                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                                     at android.view.View.layout(View.java:16694)
                                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                     at android.view.View.layout(View.java:16694)
                                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                                     at android.view.View.layout(View.java:16694)
                                                                                 	at android.view.ViewGroup.layout(ViewGroup.java:5481

**Comment by fiskurgit** [comment]
This looks like a bug unrelated to the recycler when you don't call `showIndicator(int, int)` - now fixed in 1.0.11.

Sorry for the delay responding.
